version: '2.1'
services:
  omero-data:
    container_name: omero-data
    image: omero-base
    privileged: true
    volumes:
      - ${OMERO_DATA_DIR-~/data_omero}:/data:Z
    command: "true"

  omero-init-db:
    container_name: omero-init-db
    build: omero-init-db
    volumes_from:
      - omero-data

  omero-pg:
    container_name: omero-pg
    image: postgres:9.4.10
    volumes_from:
      - omero-data
    volumes:
      - ./omero-postgres/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    env_file:
      - postgres.env
    environment:
      PGDATA: /data/postgres
    depends_on:
      - omero-init-db

  omero-server:
    container_name: omero-server
    build: omero-server
    volumes_from:
      - omero-data
    links:
      - omero-pg
    ports:
      - "${OMERO_SERVER_PORT-4064}:4064"
    env_file:
      - postgres.env

  omero-web:
    container_name: omero-web
    build: omero-web
    volumes_from:
      - omero-data
    links:
      - omero-server
    ports:
      - "${OMERO_WEB_PORT-80}:80"
      - "${OMERO_WEB_PORT_SSL-443}:443"
      - "${OMERO_WEB_PORT_DEVELOPMENT-4080}:4080"
    environment:
      OMERO_WEB_USE_SSL: "${OMERO_WEB_USE_SSL-yes}"
      OMERO_WEB_DEVELOPMENT: "${OMERO_WEB_DEVELOPMENT-no}"
